server: 
  port: 9001
spring:
  application: 
    name: smartRouteServer
eureka:
  instance:
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://192.168.1.5:8761/eureka/
zk:
  connect: 192.168.208.128:2181